;;some bits to check the parser
(require "tokenizer.scm")
(define tokstring "I am:a tok:string;with:if,then,else:,many toks;")
(define mydelim (list #\: #\, #\;))
(parse tokstring mydelim)
(string-tokenizer tokstring mydelim)
(gettokfrom (string-tokenizer tokstring  mydelim) 4)

(gettokfrom (string-tokenizer tokstring  mydelim) 5)
(define teststr "a:t:w")
(processloop (string-tokenizer "test:the:west"  mydelim))
(processloop (string-tokenizer teststr  (list #\:)))
(processloop (string-tokenizer tokstring  (list #\:)))
(processloop (string-tokenizer tokstring  mydelim))
(is-in-list? #\_ (list #\, #\; #\: #\= ))
(is-in-list? #\, (list #\, #\; #\: #\= ))
(is-in-list? #\= (list #\, #\; #\: #\= ))
(is-in-list? #\: (list #\, #\; #\: #\= ))
(is-in-list? #\; (list #\, #\; #\: #\= ))
(is-in-list? #\- (list #\, #\; #\: #\= ))