#lang mzscheme
 (require (lib "records.ss" "srfi" "57"))
;*; typed record type definitions**
;;  Copyright (C) Harald Glab-Plhak 2006

;; hygene warning: this macro transforms into calls to the record
;; accessors and predicates presumably generated by define-record.  If
;; this macro appears in a context where these accessors and
;; predicates have been shadowed, too bad.
(define-syntax rectype-def 
  (lambda (form)
    (define generateid
      (lambda (template-id . args)
        (datum->syntax-object template-id
                              (string->symbol
                               (apply string-append
                                      (map (lambda (x)
                                             (if (string? x)
                                                 x
                                                 (symbol->string
                                                  (syntax-object->datum  x))))
                                           args))))))
    (syntax-case form ()       
      ((_ type (field field-pred)  ...)
       (with-syntax
           ((constructor (generateid (syntax type) "make-" (syntax type)))
            (predicate (generateid (syntax type) (syntax type) "?"))
            ((field-get ...)
             (map (lambda (x) (generateid x (syntax type) "->"   x))
                  (syntax->list (syntax (field ...)))))
            ((field-set ...)
             (map (lambda (x) (generateid x "set-" (syntax type) "-"  x "!"))
                  (syntax->list (syntax (field ...)))))
            )
         (syntax
          (begin
            (define type (list 'type  '(field ...) '(field-pred ...)))
            (define predicate (typed-record? type))
            (define constructor (make-record type))    
            (define field  'field) ...
            (define field-get (typed-record-ref type predicate field)) ...
            (define field-set (typed-record-set! type predicate field-pred field)) ...))))
      ((_ type extended-type
          (field field-pred)  ...)
       (with-syntax
           ((constructor (generateid (syntax type) "make-" (syntax type)))                          
            (predicate (generateid (syntax type) (syntax type) "?"))
            ((field-get ...)
             (map (lambda (x) (generateid x (syntax type) "->"   x))
                  (syntax->list (syntax (field ...)))))
            ((field-set ...)
             (map (lambda (x) (generateid x "set-" (syntax type) "-"  x "!"))
                  (syntax->list (syntax (field ...)))))           
            )
         (syntax
          (begin
            (define type (list 'type   '(field ...) '(field-pred ...) extended-type))
            (define predicate (typed-record? type))
            (define constructor (make-extended-record type extended-type))    
            (define field  'field) ...
            (define field-get (typed-record-ref type predicate field)) ...
            (define field-set (typed-record-set! type predicate field-pred field)) ...))))
      )))

(define-syntax select  (
                        syntax-rules()
                         ((_  input  (predicate? body)...) 
                          (call-with-current-continuation 
                           (lambda (cont) 
                             (cond  
                               ((predicate? input) (body cont input))...))))))







;; procedural definition of the complex -- type
(define checkindex (lambda (in) (if (and(pair? in) (cdr in)) (car in) -1)))
(define cps-result (lambda (in) in))
(define cps-result-pair (lambda (first second) (cons first second)))
(define parse-ancestors (lambda (obj) 
                          (define inner (lambda (part lookup)
                                          (if (null? part)
                                              (lookup '())
                                              (inner(cdr part)
                                                    (lambda (p)
                                                      (lookup 
                                                       (if (pair? part)
                                                           (append p (list(car part))) 
                                                           (list p))))))))
                          (inner obj cps-result)))
(define check-type (lambda (type obj) 
                     (define inner (lambda (type part lookup)                                          
                                     (if (or (null? part)(null? type))
                                         (lookup '())
                                         (inner (inherit-type type) (cdr part) 
                                                (lambda (p) 
                                                  (lookup 
                                                   (if 
                                                    (pair? part) 
                                                    (append 
                                                     p
                                                     (list(simple-record? type (list(car part)))))
                                                    (list p))))))))
                     (inner type obj 
                            (lambda (lst) (same-val #t lst )))))

(define find-type (lambda (type obj) 
                    (letrec 
                        ((lookup (lambda (nextobj)
                                   (cond ((null? nextobj) #f)
                                         ((simple-record? type (list(car nextobj))) nextobj) 
                                         (else (lookup(cdr nextobj))))))) 
                      (lookup obj))))



(define find-field (lambda (fieldlist fieldname)          
                     (letrec ((innerfind (lambda (counter) 
                                           (if (eq? counter (vector-length fieldlist)) -1
                                               (if (eq? (vector-ref fieldlist counter) fieldname)
                                                   counter
                                                   (innerfind (+ counter 1))))))) (innerfind 0))))

(define make-extended-record (lambda (type extended-type)
                               (let ((thisrec (make-record type)))
                                 (lambda (recname) 
                                   (let* ((basetype (inherit-type type))                                      
                                          (basetypename (car basetype))
                                          (baserec (lambda (name) 
                                                     (if (> (length extended-type) 3)
                                                         ((make-extended-record extended-type
                                                                                (inherit-type extended-type)) name)
                                                         ((make-record extended-type) name))))
                                          (this (thisrec recname)))
                                     (append this
                                             (baserec basetypename)))))))

(define make-record
  (lambda (type) 
    (lambda(recname) 
      (let* ((fieldlist (cadr type))
             (predlist  (caddr type))
             (recfields (list->vector fieldlist))
             (values (make-vector (length fieldlist)))
             (recdef (vector (cons 'rec (car type))
                             (cons 'name recname)
                             (cons 'rec-len (length fieldlist)) 
                             (cons 'rec-types-ok (same-val #t (map symbol? predlist)))
                             (cons 'rec-valid (eq? (length fieldlist) (length predlist))) 
                             recfields values))) 
        (list recdef)))))

(define rec-type  (lambda (obj) (vector-ref  (car obj) 0))) ;; change the simple car to trace also subtypes
;; and add type checking for single inheritance 
(define rec-name (lambda (obj) (vector-ref (car obj) 1)))
(define rec-length (lambda (obj) (vector-ref (car obj) 2)))
(define rec-types-valid (lambda (obj) (vector-ref (car obj) 3)))
(define rec-validator  (lambda (obj) (vector-ref (car obj) 4)))
(define rec-fields  (lambda (obj) (vector-ref (car obj) 5)))
(define rec-values  (lambda (obj) (vector-ref (car obj) 6)))
(define inherit-type (lambda (type) 
                       (let ((subtype (list-tail type 3)))
                         (if (pair? subtype)(car subtype) '() ))))
(define pair-and-val? (lambda(paired value) (and(pair? paired)(eq? (car paired) value))))
(define pair-and-paireq? (lambda(paired value) 
                           (and(pair? paired)
                               (eq? (car paired) (car value)) 
                               (eq? (cdr paired) (cdr value)))))
(define record-type-pred (lambda (obj) (cond 
                                         ((eq? (record-type-type obj) 's) simple-record?)
                                         ((eq? (record-type-type obj) 'e) extended-record?)
                                         (else #f))))
(define record-type-type (lambda (obj) (cond 
                                         ((pair-and-val? (rec-type obj) 'rec) 's)
                                         ((pair-and-val? (rec-type obj) 'ext-rec) 'e) 
                                         (else #f))))
;;the predicates have to be changed to check the complete record not only the first inheritance
;; try to keep these bits more simple may be by redefining the internal representation of the record
(define typed-record? (lambda (type)
                        (lambda (obj)
                          (check-type type obj))))


(define extended-record? (lambda (type obj)                  
                           (let ((innertype (inherit-type type)))
                             (if (and (simple-record? type (vector-ref obj 1))
                                      (simple-record? innertype (vector-ref obj 2))) 'e #f))))


(define simple-record? (lambda (type obj)                  
                         (and (list? obj)(vector? (car obj))                         
                              (eq? (vector-length (car obj)) 7)
                              (pair-and-paireq? (rec-type obj ) (cons 'rec  (car type)))
                              (pair-and-val? (rec-name obj ) 'name)                         
                              (pair-and-val? (rec-length obj ) 'rec-len)
                              (pair-and-paireq? (rec-types-valid obj ) (cons 'rec-types-ok #t))
                              (pair-and-paireq? (rec-validator obj ) (cons 'rec-valid #t))
                              )))

(define record-length (lambda(obj) (if (typed-record? obj) (cdr (rec-length obj)) 0))) 


;; remarks: - have to think about what's happen when a type is set in itselef like (set-rtype-f1! typeobj typeobj)
;; does this make sense or should it be forbidden check the possible cases
;; - build up a record // type registry where all rec-defs are stored flat
;; - build the registry to enable records type information to be retrieved if 
;; needed - so e.g. the type check can be optimized by changing the internal representation 
;; thingk about storing values in a way they can also be adressed positional by a lambda calcolating the position for a name once
(define typed-record-set! 
  (lambda (type type-pred? field-pred? field) 
    (lambda(obj value)
      (let ((refobj (find-type type obj)))
        (if (and refobj (type-pred? refobj) (field-pred? value))
            (let* ((index (find-field (rec-fields refobj) field))
                   (do-set (> index -1)))
              (if do-set (vector-set! (rec-values refobj) index value) (display "not set field not found")))(display "type error"))))))

(define typed-record-ref (lambda (type type-pred? field) 
                           (lambda(obj)
                             (let ((refobj (find-type type obj)))
                               (if (type-pred? refobj)
                                   (let*
                                       ((index (find-field (rec-fields refobj) field))
                                        (do-set (> index -1)))
                                     (if do-set (vector-ref (rec-values refobj) index) "n/a #f")))))))

;; code no longer used I only take it for showing how variable arguments can be handled
;; replace it by different definitions


(define same-val (lambda (val vallist) (letrec ((loop (lambda (plist) (cond 
                                                                        ((null? plist) #t)
                                                                        ((not (eq? (car plist) val )) #f )
                                                                        ((pair? plist) (loop (cdr plist)))))))
                                         (loop vallist))))



;;(select ((rtype (actionlist)) (utype2 (actionlist)) (newtype (actionlist)))
(rectype-def rtype  (f1 rtype?) (f2 number?) (f3 vector?)) 
(rectype-def newtype rtype  (f4 string?) (f5 list?) (f6 newtype?) (f7 newtype?) )
(rectype-def nexttype newtype  (f9 string?) (f10 vector?) (f13 nexttype?) (f8 newtype?) )
(rectype-def compltype nexttype  (for  string?) (the vector?) (last nexttype?) (test newtype?) )
;; for this kind of type I have to check if no ;;fieldname is duplicated
;; (testsyn try (west test))
;; (try->west)


(display (inherit-type newtype))(newline)
(display (inherit-type rtype))(newline)
(display compltype)(newline)
(define complobj (make-compltype 'lastobj))
(define lastobj (make-nexttype 'lastobj))
(define typeobj (make-rtype 'typeobj)) ;; change constructor to get the type information inside the macro
(define extobj (make-newtype 'extobj)) 
(display "select result")
(select typeobj 
        (rtype? (lambda(cont typeobj) 'called-with-cont))  
        (nexttype? (lambda(cont typeobj) (display(+ 2 6)) typeobj))
        (newtype? (lambda(cont typeobj)cont )))

(check-type rtype typeobj)
(check-type newtype extobj)
(check-type nexttype lastobj)
(check-type compltype complobj)
(display "type")(newline)
(display (find-type rtype lastobj))(newline)
(display (find-type compltype lastobj))(newline)
(display (find-type nexttype lastobj))(newline)
(display "end-type")(newline)
(display "simple rec")(newline)
(display  typeobj)(newline)
(display "complex rec")(newline)
(display  extobj)(newline)
(display "more complex rec")(newline)
(display  lastobj)(newline)
(display "most complex rec")(newline)
(display  complobj)(newline)
(display "cps parse rec") (newline)
(display (parse-ancestors complobj))(newline)
(rtype->f3 typeobj)
(set-rtype-f3! typeobj "bla")
(set-newtype-f4! extobj "bla")
(rtype->f3 typeobj)
(set-rtype-f2! complobj 77)
(set-newtype-f4! extobj "test") 
(display (newtype->f4 extobj))
(set-rtype-f2! typeobj 5)
(rtype->f3 typeobj)
(set-rtype-f1! complobj typeobj)
(rtype->f2 complobj)
(rtype->f2 typeobj)
(set-rtype-f3! typeobj '#( 1 1 3 4))
(set-rtype-f2! typeobj '#( 1 1 3 4))
(rtype->f3 typeobj)
(rtype->f2 typeobj)
(rtype->f1 complobj)